import ColorType from '@/types/color.type';

export type IconType =
  | 'character'
  | 'logo'
  | 'welcome'
  | 'seeking-house'
  | 'male'
  | 'female'
  | 'dont-mind-sex'
  | 'dont-mind-pet'
  | 'pet-lover'
  | 'none-pet-lover'
  | 'studio-officetel'
  | 'villa-townhouse'
  | 'apartment'
  | 'single-family-house'
  | 'smoke'
  | 'none-smoke'
  | 'right-arrow'
  | 'left-arrow'
  | 'expand-arrow'
  | 'close'
  | 'google-logo'
  | 'invisible'
  | 'kakaotalk-logo'
  | 'kakaotalk-logo-text'
  | 'visible'
  | 'alarm-exist'
  | 'alarm-none'
  | 'avatar'
  | 'paper-clip'
  | 'send'
  | 'camera'
  | 'prev'
  | 'next'
  | 'back'
  | 'monthly-rental-price'
  | 'semi-monthly-rental-price'
  | 'year-rental-price'
  | 'dont-mind-rental-price'
  | 'one-person'
  | 'two-people'
  | 'three-people'
  | 'dont-mind-people'
  | 'done'
  | 'mini-heart'
  | 'page-prev'
  | 'page-next'
  | 'search'
  | 'heart'
  | 'share'
  | 'mini-smoke'
  | 'mini-none-smoke'
  | 'icon-male'
  | 'icon-female'
  | 'icon-gender-free'
  | 'pet-heart'
  | 'pet-hate'
  | 'pet-circle'
  | 'fill-heart'
  | 'edit'
  | 'delete'
  | 'edit-avatar';

export type CustomIconType = {
  fill?: ColorType;
  stroke?: ColorType;
};

export type IconDirectionType = 'left' | 'right' | 'top' | 'bottom';
